version: '3.4'

services:
  database:
    build:
      context: database
    env_file:
      - database/.env
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build:
      context: api
      target: development
    env_file:
      - api/.env
    ports:
      - '3000:3000'

volumes:
  mysql_data:
