openapi: 3.1.0
info:
  version: 0.1.0
  title: <%- projectName %> - API documentation
  description: |
    Default API documentation created by generator-koa2-api-generator for <%- projectName %> project.
  contact:
    name: Contact example name
    url: http://www.example.com
    email: example@example.com
  termsOfService: http://www.example.com
  license:
    name: Replace with some license or remove this section.
    url: http://www.example.com
tags:
  - name: API endpoints
