env:
  browser: true
  es2021: true

extends: ['eslint:recommended', 'standard', 'prettier']

overrides:
  [
    {
      files: ['src/**/*.js'],
      extends: ['plugin:openapi/recommended'],
      plugins: ['openapi'],
    },
    {
      env: { node: true },
      files: ['__tests__/**/*.js'],
      extends: ['plugin:jest/recommended'],
      plugins: ['jest'],
      rules: { jest/expect-expect: 0, no-template-curly-in-string: 0 },
    },
  ]

parserOptions: { ecmaVersion: 'latest', sourceType: 'module' }
