version: '3.4'

services:
  database:
    build:
      context: database
    env_file:
      - database/.env
    restart: always

  api:
    build:
      context: api
    env_file:
      - api/.env
    ports:
      - '3000:3000'
