version: '3.4'

services:
  database:
    build:
      context: database
    env_file:
      - database/.env
    restart: always

  api:
    build:
      context: <%- project_name %>
    env_file:
      - <%- project_name %>/.env
    ports:
      - '3000:3000'
